### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by dilab** [EventSaucePHP/BackOff#3]
Looks interesting, it will be helpful if more explanation of its use case. Is it to handle concurrency issue when commands are executed on the same aggregate?

**Comment by frankdejonge** [comment]
It is useful for when you consume events and want to handle a consumer with improved resilience. It'll be used for the upcoming outbox package that will ship by default with a back-off strategy.

**Comment by dilab** [comment]
cool. looking forward to that.
