### ISSUE TITLE
Jitter after backoff time has exceeded

### ISSUE THREAD

**Issue by ghost** [EventSaucePHP/BackOff#4]
Would it be a useful addition to this library if we add an option to add jitter, but only after the backoff time has exceeded?

We have a use-case where we need to respect a client's API backoff limits and therefor need to have Jitter but only after the backoff period is exceeded.

**Comment by frankdejonge** [comment]
@DaanRG how about: https://github.com/EventSaucePHP/BackOff/pull/7
