### ISSUE TITLE
Infinite number of retries

### ISSUE THREAD

**Issue by dam2k** [EventSaucePHP/BackOff#5]
Thanks for this cool library!
What about creating the possibility to have an **infinite number of retries**?
For ex. we could loop forever, with backoff timings, if maxTries is not >0 (a very simple hack I already done for myself):

`if ($tries > $this->maxTries) {...`
becomes
`if ($this->maxTries>0 && $tries > $this->maxTries) {...`

WDYT?

**Comment by frankdejonge** [comment]
lemme see what I can do

**Comment by frankdejonge** [comment]
@dam2k how about: https://github.com/EventSaucePHP/BackOff/pull/6

**Comment by dam2k** [comment]
Thank you!

**Comment by dam2k** [comment]
Thank you!
